export const ACTION_TYPE = {
  SET_USER: "SET_USER",
  SET_PRODUCT_DATA: "SET_PRODUCT_DATA",
  RESET_PRODUCT_DATA: "RESET_PRODUCT_DATA",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  ADD_TO_CART: "ADD_TO_CART",
  FETCH_CART_START: "FETCH_CART_START",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  FETCH_CART_ERROR: "FETCH_CART_ERROR",
  CHANGE_QUANTITY: "CHANGE_QUANTITY",
};
